language: java
jdk: oraclejdk8
sudo: false

before_install: chmod +x gradlew
install:
  - ""
script:
  - ./gradlew --continue build check
  - bash <(curl -s https://codecov.io/bash)
  - rm ~/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - ~/.gradle

notifications:
  email: false
